SimpleERP/urls.py
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from web.views import department, user, admin, account, task, parts, chart

urlpatterns = [
    re_path(
        r"media/(?P<path>.*)$",
        serve,
        {"document_root": settings.MEDIA_ROOT},
        name="media",
    ),
    # 部门管理
    path("depart/list/", department.depart_list),
    path("depart/add/", department.depart_add),
    path("depart/<int:nid>/del/", department.depart_del),
    path("depart/<int:nid>/edit/", department.depart_edit),  # 利用正则表达式来进行解析
    path("depart/multi/", department.depart_multi),
    # 员工管理
    path("user/list/", user.user_list),
    path("user/model/form/add/", user.user_add_model_form),
    path("user/<int:nid>/edit/", user.user_edit),
    path("user/<int:nid>/del/", user.user_del),
    # 管理员账户
    path("admin/list/", admin.admin_list),
    path("admin/add/", admin.admin_add),
    path("admin/<int:nid>/edit/", admin.admin_edit),
    path("admin/<int:nid>/del/", admin.admin_del),
    path("admin/<int:nid>/reset/", admin.admin_reset),
    # 用户登录
    path("login/", account.login),
    path("logout/", account.logout),
    path("image/code/", account.image_code),
    path("ajax/task/", task.ajax_task),
    path("ajax/add/", task.ajax_add),
    # 数据统计
    path("chart/list/", chart.chart_list),
    # 零件管理
    path("part/list/", parts.part_list),
    path("part/add/", parts.part_add),
    path("part/<int:nid>/edit/", parts.part_edit),
    path("part/<int:nid>/delete/", parts.part_delete),
    # REST框架的登录和注销视图
    path("", include("api.urls")),
]

"""urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]"""

api/urls.py
#!usr/env/python3
# -*- coding: utf-8 -*-

"""
# File       : urls.py
# Time       : 2023/4/25 16:32
# Author     : Ron
# version    : python 3.9
# software   : Pycharm
# Description：
"""

from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from api.views import partsAPI

urlpatterns = [
    path('parts/', partsAPI.PartsList.as_view()),
    path('parts/<int:pid>/', partsAPI.PartsDetail.as_view()),
    # path('users/', partsAPI.UserList.as_view()),
    # path('users/<int:id>/', partsAPI.UserDetail.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

web/models.py
from django.db import models

# Create your models here.


class Admin(models.Model):
    """管理员"""

    user = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.user


class Department(models.Model):
    """部门表"""

    department_name = models.CharField(verbose_name="部门名称", max_length=32)
    employees_num = models.IntegerField(verbose_name="员工人数")

    # 输出对象时，如果想要定制显示的内容，可以定义一个__str__方法
    def __str__(self):
        return self.department_name


class UserInfo(models.Model):
    """员工表"""

    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=63)
    age = models.IntegerField(verbose_name="年龄")
    create_time = models.DateField(verbose_name="入职时间")

    # 置空
    depart = models.ForeignKey(
        to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL
    )

    # 在Django中做约束
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )

    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class AjaxTask(models.Model):
    """任务"""

    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时"),
    )

    level = models.SmallIntegerField(
        verbose_name="级别", choices=level_choices, default=1
    )
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")

    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)


class Parts(models.Model):
    """零件"""

    pid = models.CharField(verbose_name="零件编号", max_length=64)
    name = models.CharField(verbose_name="零件名称", max_length=32)
    unit = models.CharField(verbose_name="计量单位", max_length=32)
    amount = models.IntegerField(verbose_name="库存量")
    price = models.FloatField(verbose_name="单价")
    store = models.CharField(verbose_name="仓库存储位置", max_length=64)
    description = models.CharField(verbose_name="附加描述", max_length=128)

    def __str__(self):
        return self.name


class Sales(models.Model):
    """订单管理"""

    COMPANY = "公司"
    SMALL_BUSINESS = "小型企业"
    CONSUMER = "消费者"
    CUSTOMER_IN_CHOICES = [(COMPANY, "公司"), (SMALL_BUSINESS, "小型企业"), (CONSUMER, "消费者")]

    bid = models.CharField(verbose_name="订单号", max_length=64)
    name = models.ForeignKey(
        verbose_name="商品名称",
        to="Parts",
        to_field="id",
        on_delete=models.CASCADE,
    )
    sale_num = models.IntegerField(verbose_name="销售数量", default=0)
    profit = models.FloatField(verbose_name="销售利润")
    customer = models.CharField(
        verbose_name="采购方",
        choices=CUSTOMER_IN_CHOICES,
        max_length=64,
        default=SMALL_BUSINESS,
    )
    time = models.DateTimeField(auto_now=True)

web/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <!-- 按钮 -->
    <div class="row mb-1">
        <div class="col-md-6">
            <a type="button" class="btn btn-success" href="/admin/add/">添加管理员</a>
        </div>
        <div class="col-md-6">
            {#      bootstrap5 样式      #}
            <form class="d-flex justify-content-end" role="search" method="get">
                <input class="form-control me-2 w-auto" type="search" placeholder="关键字搜索"
                       aria-label="Search"
                       name="q" value="{{ search_data }}">
                <button class="btn btn-outline-success" type="submit">搜索</button>
            </form>
        </div>
    </div>


    <!-- 面板 -->
    <div class="card">
        <div class="card-body table-responsive" style="padding: 1vw 1vw 0;">
            <h5 class="card-title">管理员列表</h5>
            <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">用户名</th>
                <th scope="col">密码</th>
                <th scope="col">重置密码</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <th scope="row">{{ item.id }}</th>
                    <td>{{ item.user }}</td>
                    <td>******</td>
                    <td><a href="/admin/{{ item.id }}/reset/">重置密码</a></td>
                    <td>
                        <a type="button" class="btn btn-primary btn-sm" href="/admin/{{ item.id }}/edit/">编辑</a>

                        <a type="button" class="btn btn-danger btn-sm"
                           href="/admin/{{ item.id }}/del/">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="input-group">
            <ul class="pagination justify-content-center">
                {{ page_string }}
            </ul>
        </div>
    </div>
    </div>
{% endblock %}

web/templates/change.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default container">
    <div class="panel-heading">{{ title }}</div>
    <div class="panel-body">
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form  %}
            <div class="form-group">
                <label>{{ field.label }}</label>
                {{ field }}
                <span style="color: red;">{{ field.errors.0 }}</span>
            </div>

            {% endfor %}
            <button type="submit" class="btn btn-primary"> 提 交</button>
        </form>
    </div>
</div>
{% endblock %}

web/templates/chart_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-lg-6 grid-margin">
                <div class="card" style="margin: 1rem 0.5rem">
                    <div class="card-body">
                        <h5 class="card-title">销售额</h5>
                        <div style="font-size: 3rem; color: #4b88a6; display: flex; justify-content: center">
                            ￥
                            <p class="card-text text-center" id="sale-profit">
                                {{ total_profit }}</p>
                            万
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6">
                <div class="card" style="margin: 1rem 0.5rem">
                    <div class="card-body">
                        <h5 class="card-title">今年销售数量</h5>
                        <p class="card-text text-center" id="products"
                           style="font-size: 3rem; color: orange">{{ total_products }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-5">
                <div class="card" style="margin: 1rem 0.5rem">
                    <div class="card-body">
                        <h5 class="card-title" style="margin-bottom: 1rem">客户市场细分销售额</h5>
                        <div id="chartPie" style="min-height: 38rem"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-7">
                <div class="card" style="margin: 1rem 0.5rem">
                    <div class="card-body">
                        <h5 class="card-title">销售额趋势变化</h5>
                        <div id="chartBarOne" style="min-height: 38rem"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card" style="margin: 1rem 0.5rem;">
                    <div class="card-body">
                        <h5 class="card-title">类别利润</h5>
                        <div id="chartBarTwo" style="min-height: 38rem"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="https://cdn.bootcdn.net/ajax/libs/d3/7.8.5/d3.min.js"></script>
    <script type="text/javascript" src="https://fastly.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
    <script type="text/javascript">
        {#  利用D3实现数字丝滑过渡  #}
        const profitDisplay = d3.select("#sale-profit");
        const productsNumDisplay = d3.select("#products")

        // 设置初始值
        const initialValue = 0.00;
        // 设置动画持续时间
        const animationDuration = 1000;

        /**
         * 数字展示过渡动画函数，精度为小数点后两位，初始值为0.00
         * @param element 展示的html标签
         * @param targetValue 目标值
         */
        function updateNumberFloat(element, targetValue) {
            // 使用D3的过渡方法，从当前值过渡到新值
            element.transition()
                .duration(animationDuration) // 过渡时间为1秒
                .tween("text", function () {
                    const interpolator = d3.interpolateNumber(initialValue, targetValue);
                    return function (t) {
                        // 更新div的文本内容为插值结果
                        element.text(interpolator(t).toFixed(2));
                    };
                })
        }

        /**
         * 整数展示过渡动画函数，初始值为0
         * @param element 展示的html标签
         * @param targetValue 目标值
         */
        function updateNumberInt(element, targetValue) {
            // 使用D3的过渡方法，从当前值过渡到新值
            element.transition()
                .duration(animationDuration) // 过渡时间为1秒
                .tween("text", function () {
                    const interpolator = d3.interpolateNumber(0, targetValue);
                    return function (t) {
                        // 更新div的文本内容为插值结果
                        element.text(Math.round(interpolator(t)));
                    };
                })
        }

        // 调用动画函数
        updateNumberFloat(profitDisplay, {{ total_profit }});
        updateNumberInt(productsNumDisplay, {{ total_products }})

        {# 客户市场细分销售额 #}
        let chartPieDom = document.getElementById('chartPie');
        let chartPie = echarts.init(chartPieDom);
        let optionOne;

        optionOne = {
            tooltip: {
                trigger: 'item'
            },
            legend: {
                top: '5%',
                left: 'center'
            },
            toolbox: {
                show: true,
                feature: {
                    mark: {show: true},
                    dataView: {show: true, readOnly: false},
                    restore: {show: true},
                    saveAsImage: {show: true}
                }
            },
            series: [
                {
                    name: '客户市场细分销售额',
                    type: 'pie',
                    radius: ['40%', '70%'],
                    avoidLabelOverlap: false,
                    itemStyle: {
                        borderRadius: 10,
                        borderColor: '#fff',
                        borderWidth: 2
                    },
                    label: {
                        show: false,
                        position: 'center'
                    },
                    emphasis: {
                        label: {
                            show: true,
                            fontSize: 40,
                            fontWeight: 'bold'
                        }
                    },
                    labelLine: {
                        show: false
                    },
                    data: [
                        {value: {{ company }}, name: '公司'},
                        {value: {{ business }}, name: '小企业'},
                        {value: {{ consumer }}, name: '消费者'},
                    ]
                }
            ]
        };

        optionOne && chartPie.setOption(optionOne);

        {# 销售趋势变化图 #}
        let chartBarDomOne = document.getElementById('chartBarOne')
        let chartBarOne = echarts.init(chartBarDomOne);

        optionTwo = {
            tooltip: {
                trigger: 'axis',
                axisPointer: {
                    type: 'cross',
                    crossStyle: {
                        color: '#999'
                    }
                }
            },
            toolbox: {
                feature: {
                    dataView: {show: true, readOnly: false},
                    magicType: {show: true, type: ['line', 'bar']},
                    restore: {show: true},
                    saveAsImage: {show: true}
                }
            },
            legend: {
                data: ['销售额', '销售数量']
            },
            xAxis: [
                {
                    type: 'category',
                    data: ['2023-01', '2023-02', '2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09', '2023-10', '2023-11', '2023-12'],
                    axisPointer: {
                        type: 'shadow'
                    }
                }
            ],
            yAxis: [
                {
                    type: 'value',
                    name: '月度销售额',
                    min: 0,
                    max: 80,
                    interval: 10,
                    axisLabel: {
                        formatter: '{value} 万元'
                    }
                },
                {
                    type: 'value',
                    name: '月度销售数量',
                    min: 0,
                    max: 8000,
                    interval: 1000,
                    axisLabel: {
                        formatter: '{value} 件'
                    }
                }
            ],
            series: [
                {
                    name: '销售额',
                    type: 'bar',
                    tooltip: {
                        valueFormatter: function (value) {
                            return value + ' 万元';
                        }
                    },
                    data: {{ month_profit }}
                },
                {
                    name: '销售数量',
                    type: 'line',
                    yAxisIndex: 1,
                    tooltip: {
                        valueFormatter: function (value) {
                            return value + ' 件';
                        }
                    },
                    data: {{ month_sale_num }}
                }
            ]
        }
        optionTwo && chartBarOne.setOption(optionTwo);

        {#  产品类别利润  #}
        let chartBarDomTwo = document.getElementById('chartBarTwo');
        let chartBarTwo = echarts.init(chartBarDomTwo)

        optionThree = {
            title: {
                text: '产品类别利润'
            },
            tooltip: {
                trigger: 'axis',
                axisPointer: {
                    type: 'shadow'
                }
            },
            legend: {},
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            xAxis: {
                type: 'value',
                boundaryGap: [0, 0.01]
            },
            yAxis: {
                type: 'category',
                data: ['机械臂', '螺丝', '滑动变阻器',
                    '万向轮', '驱动电机', '轴承', '亚克力底盘']
            },
            series: [
                {
                    name: '2023',
                    type: 'bar',
                    tooltip: {
                        valueFormatter: function (value) {
                            return value + ' 万元';
                        }
                    },
                    data: {{ category_profit }}
                },
            ]
        };
        optionThree && chartBarTwo.setOption(optionThree);
    </script>
{% endblock %}

web/templates/depart_add.html
{% extends 'layout.html' %}



{% block content %}
<div class="card container" style="padding: 1vw 1vw 0">
    <div class="card-body">
        <h3 class="card-title">添加部门</h3>
        <form method="post">
            {% csrf_token %}
            {% for field in form  %}
            <div class="mb-3" style="margin-bottom: 1vw">
                <label class="label-info">{{ field.label }}</label>
                {{ field }}
                <span style="color: red;">{{ field.errors.0 }}</span>
{#                <input type="text" class="form-control" placeholder="{{ field.label }}" name="{{ field.name}}">#}
            </div>

            {% endfor %}
            <button type="submit" class="btn btn-primary">提 交</button>
        </form>
    </div>
</div>

{% endblock %}

web/templates/error.html
{% extends 'layout.html' %}

{% block content %}
<div class="alert alert-danger" role="alert">{{ msg }}</div>
{% endblock %}

web/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>信息管理系统</title>
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.css" rel="stylesheet">
    <style>
        {% block css %}

        {% endblock %}

        .navbar {
            border-radius: 0;
        }

        a {
            text-decoration: none;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd; margin-bottom: 20px">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">山恩科技ERP系统</a>
        <button class="navbar-toggler" type="button"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/chart/list/">数据统计</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/part/list/">零件管理</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        人力资源管理
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/depart/list/">部门管理</a></li>
                        <li><a class="dropdown-item" href="/user/list/">员工管理</a></li>
{#                        <li class="dropdown-item"><a href="/order/list/">工单管理</a></li>#}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin/list/">管理员账户</a>
                </li>
            </ul>

            <ul class="navbar-nav dropdown-menu-end mb-2">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ request.session.info.name }}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">个人中心</a></li>
                        <li><a class="dropdown-item" href="/logout/">退出登录</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid" style="min-height: calc(100vh - 70px)">
    {% block content %}

    {% endblock %}
</div>
<footer class="footer" style="background: #e3f2fd; height: 50px; display: flex; justify-content: center; align-items: center">
    <div>
        <span class="text-muted d-block text-center text-md-center d-md-inline-block">Copyright (c) 2023 By admin</span>
    </div>
</footer>

<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.7.1/jquery.js"></script>
{% block js %}

{% endblock %}
</body>
</html>

web/templates/part_add.html
{% extends 'layout.html' %}}

{% block  content %}
    <div class="card">
        <div class="card-body">
        <h4 class="card-title">新建零件</h4>
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form  %}
                <div class=mb-3">
                    <label class="form-label">{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary" style="margin: 20px 0">提 交</button>
            </form>
        </div>
    </div>

{% endblock %}

web/templates/task_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">AjaxTask</div>
            <div class="panel-body">
                <form id="formAdd" novalidate>
                    <div class="clearfix">
                        {% for field in form %}
                            <div class="col-xs-6">
                                <div class="form-group" style="position: relative; margin-bottom: 20px">
                                    <label>{{ field.label }}</label>
                                    {{ field }}
                                    <span class="error-msg" style="color: red; position: absolute"></span>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                    <div class="col-xs-12">
                        <button id="btnAdd" type="button" class="btn btn-primary"> 提 交</button>
                    </div>
                </form>
            </div>


        </div>
        <div class="panel panel-primary">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                任务列表
            </div>

            <!-- Table -->
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>标题</th>
                    <th>级别</th>
                    <th>负责人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.title }}</td>
                        <td>{{ item.get_level_display }}</td>
                        <td>{{ item.user.user }}</td>
                        <td>
                            <a type="button" class="btn btn-primary btn-xs" href="/num/{{ item.id }}/edit/">编辑</a>

                            <a type="button" class="btn btn-danger btn-xs"
                               href="/num/{{ item.id }}/del/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>


    <div>
        <h1>Ajax学习</h1>
        <h3>示例1</h3>
        <input id="btn1" type="button" class="btn btn-primary" value="提 交1">

        <h3>示例3</h3>
        <form id="form3">
            <input type="text" name="user" placeholder="姓名">
            <input type="text" name="age" placeholder="年龄">
            <input type="text" name="email" placeholder="邮箱">
            <input type="text" name="intro" placeholder="介绍">
        </form>
        <input id="btn3" type="button" class="btn btn-primary" value="提 交">
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            // 页面加载完成之后代码自动执行
            bindBtn1Event();

            bindBtn3Event();

            bindBtnAddEvent();
        })


        function bindBtn3Event() {
            $("#btn3").click(function () {
                $.ajax({
                    url: '/ajax/task/',
                    type: 'post',
                    data: $('#form3').serialize(),
                    datatype: 'JSON',
                    success: function (res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })
        }

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                $(".error-msg").empty();
                $.ajax({
                    url: '/ajax/add/',
                    type: 'post',
                    data: $('#formAdd').serialize(),
                    dataType: 'JSON',       // 因为一个字母大小写的问题而耽误了3个小时来找bug :(
                    success: function (res) {
                        if (res.status) {
                            alert("添加成功");
                            // JS刷新页面，重新载入
                            window.location.reload();
                        } else {
                            {#console.log(res.error);#}
                            $.each(res.error, function (name, data) {
                                // console.log(name, data);
                                $("#id_" + name).next().text(data[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

web/templates/user_add_model_form.html
{% extends 'layout.html' %}}
{% load static %}
{% block css %}
    <link rel="stylesheet" href={% static "plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" %}>
{% endblock %}

{% block  content %}
    <div class="card container">
    <div class="card-body">
        <h4 class="card-title">新建用户</h4>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form  %}
            <div class="mb-3" style="margin-bottom: 1vw">
                <label class="label-info">{{ field.label }}</label>
                {{ field }}
                <span style="color: red;">{{ field.errors.0 }}</span>
{#                <input type="text" class="form-control" placeholder="{{ field.label }}" name="{{ field.name}}">#}
            </div>

            {% endfor %}
            <button type="submit" class="btn btn-primary">提 交</button>
        </form>
    </div>
</div>

{% endblock %}

{% block js %}
    <script src={% static "plugins/bootstrap-datepicker/js/bootstrap-datepicker.js" %}></script>
    <script src={% static "plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js" %}></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            });

        })
    </script>
{% endblock %}

web/templates/user_list.html
{% extends "layout.html" %}

{% block content %}
    <!-- 按钮 -->
    <div style="margin-bottom: 15px">
        <a type="button" class="btn btn-success" href="/user/model/form/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            新建用户
        </a>
    </div>
    <!-- 面板 -->
    <div class="card">
        <div class="card-body table-responsive" style="padding-bottom: 0">
            <!-- Default panel contents -->
            <h4 class="card-title">用户列表</h4>
            <!-- Table -->
            <table class="table card-table table-hover table-vcenter text-nowrap text-center datatable">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>年龄</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in query_set %}
                    <tr>
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.name }}</td>
                        <td>{{ item.age }}</td>
                        <td>{{ item.create_time|date:'Y-m-d' }}</td>
                        <!-- Django3取时间的格式item.create_time|date:'Y-m-d H:m:s' -->
                        <td>{{ item.get_gender_display }}</td>  <!-- 直接获取元组里的数据-->
                        <td>{{ item.depart.department_name }}</td>
                        <td>
                            <a type="button" class="btn btn-primary btn-md" href="/user/{{ item.id }}/edit/">编辑</a>

                            <a type="button" class="btn btn-danger btn-md" href="/user/{{ item.id }}/del/"
                               >删除</a>

                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>

{% endblock %}